### ISSUE TITLE
Debug file: PatternLab.json. won't build

### ISSUE THREAD

**Issue by AndrewLeedham** [pattern-lab/patternengine-node-handlebars#7]
I am using Pattern Lab Node `v2.0.0` on `Windows`, using the `gulp` configuration. Along with pattern-engine-node-handlebars `v1.0.2`.

##### Expected Behavior
Running `patternlab:build` or `patternlab:serve` with `"debug": true` in the `patternlab-config.json`, should generate a patternlab.json file containing both mustache and handlebars engine references.

##### Actual Behavior
Following error occurs during the build process:
```
[12:06:40] TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at printDebug (C:\wamp64\www\plabh\node_modules\patternlab-node\core\lib\patternlab.js:256:51)
    at Object.build (C:\wamp64\www\plabh\node_modules\patternlab-node\core\lib\patternlab.js:610:7)
    at build (C:\wamp64\www\plabh\gulpfile.js:105:34)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at asyncRunner (C:\wamp64\www\plabh\node_modules\async-done\index.js:36:18)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

##### Steps to Reproduce

1. Fresh prebuilt install of `edition-node-gulp`.
2. `npm install --save-dev patternengine-node-handlebars`
3. Set `"debug": true` in `patternlab-config.json`
4. Run `gulp patternlab:serve`

**Comment by Nubville** [comment]
@AndrewLeedham did you ever figure out what you had to do to solve this?

**Comment by AndrewLeedham** [comment]
> @AndrewLeedham did you ever figure out what you had to do to solve this?

Unfortunately not, ended up using the mustache patternengine.
